{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h4>
    {if $browse_start.node_id|ne( 1 )}
        <a href="ezajaxuploader::browse::{$browse_start.parent_node_id}::{$class.id}"><img src={'up-16x16-grey.png'|ezimage()} alt="{'Su di un livello'|i18n( 'openpa' )}" /></a>
    {/if}
    {foreach $browse_start.path as $pnode}
        <a href="ezajaxuploader::browse::{$pnode.node_id}::{$class.id}">{$pnode.name|wash()}</a> /
    {/foreach}
    {$browse_start.name|wash()}
</h4>
<table class="list ajaxuploader-locations">
    <tr>
        <th class="tight"></th>
        <th>{'Nome'|i18n( 'openpa' )}</th>
        <th>{'Tipo'|i18n( 'openpa' )}</th>
        <th>{'Sezione'|i18n( 'openpa' )}</th>
    </tr>
    {foreach $browse.items as $item sequence array( 'bgdark', 'bglight' ) as $c}
    <tr class="{$c}">
        <td>
            <input type="radio" name="UploadLocation" value="{$item.node.node_id}"
                id="ajaxuploader-location{$item.node.node_id}"
                {cond( $item.can_create|not(), ' disabled="disabled"', '' )}
                {cond( $item.node.node_id|eq( $default_parent_node.node_id ), ' checked="checked"', '' )} />
        </td>
        <td>
            <label for="ajaxuploader-location{$item.node.node_id}">
            {if $item.has_child}
                <a href="ezajaxuploader::browse::{$item.node.node_id}::{$class.id}">{$item.node.name|wash()}</a>
            {else}
                {$item.node.name|wash()}
            {/if}
            </label>
        </td>
        <td>
            <label for="ajaxuploader-location{$item.node.node_id}">
            {$item.node.class_name|wash()}
            </label>
        </td>
        <td>
            <label for="ajaxuploader-location{$item.node.node_id}">
            {fetch( section, object, hash( 'section_id', $item.node.object.section_id ) ).name|wash()}
            </label>
        </td>
    </tr>
    {/foreach}
</table>
<div class="pagination-container text-center">
  <ul class="pagination">
    <li>
        {if $browse.has_prev}
            <a href="ezajaxuploader::browse::{$browse_start.node_id}::{$class.id}::{$browse.offset|sub( $browse.limit )}">&laquo;&nbsp;{'Precedente'|i18n( 'openpa' )}</a>
        {else}
            <span>&laquo;&nbsp;{'Precedente'|i18n( 'openpa' )}</span>
        {/if}
    </li>
    <li>
        {if $browse.has_next}
            <a href="ezajaxuploader::browse::{$browse_start.node_id}::{$class.id}::{$browse.offset|sum( $browse.limit )}">{'Successivo'|i18n( 'openpa' )}&nbsp;&raquo;</a>
        {else}
            <span>{'Successivo'|i18n( 'openpa' )}&nbsp;&raquo;</span>
        {/if}
    </li>    
  </ul>
</div>
