{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={'ezjscore/call'|ezurl} method="post" class="ajaxuploader-location">
    <fieldset>
        <legend>{"Step 2/3: Scegli una collocazione per il nuovo oggetto '%class'"|i18n( 'openpa', '', hash( '%class', $class.name|wash() ) )}</legend>
        <p>{'<em>%file</em> caricato.'|i18n( 'design/admin2/ajaxupload', '', hash( '%file', $file.original_filename|wash() ) )}</p>
        <p>{"Scegli una collocazione per l'oggetto '%class' che verrà creato."|i18n( 'openpa', '', hash( '%class', $class.name|wash() ) )}</p>
        <div class="ajaxuploader-browse">
            {include uri="design:ajaxuploader/browse.tpl" browse_start=$browse_start class=$class browse=$browse default_parent_node=$default_parent_node}
        </div>

        <p class="ajaxuploader-button-bar">
            <input type="hidden" name="UploadOriginalFilename" value="{$file.original_filename|wash()}" />
            <input type="hidden" name="UploadName" value="{$name|wash()}" />
            <input type="hidden" name="UploadFile" value="{$file.filename|wash()}" />
            <input type="submit" class="defaultbutton btn btn-primary pull-right" value="{'Seleziona'|i18n( 'openpa' )}" />
            <a href="#" class="window-cancel btn btn-danger pull-left">{'Chiudi'|i18n( 'openpa' )}</a>
            <span class="ajaxuploader-error"></span>
        </p>
    </fieldset>
</form>
