{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={'ezjscore/call'|ezurl} method="post" class="ajaxuploader-preview">
    <fieldset>
        <legend>{"Step 3/3: Anterprima di '%name' (%class)"|i18n( 'openpa', '', hash( '%name', $object.name|wash(), '%class', $object.class_name|wash() ) )}</legend>

        {node_view_gui content_node=$object.main_node view=line}

        <p class="ajaxuploader-button-bar">
            <input type="submit" class="defaultbutton btn btn-primary pull-right" value="{'Aggiungi'|i18n( 'openpa' )}" />
            <a href="#" class="window-cancel btn btn-danger pull-left">{'Chiudi'|i18n( 'openpa' )}</a>
            <span class="ajaxuploader-error"></span>
        </p>
    </fieldset>
</form>
