{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={'ezjscore/call'|ezurl} method="post" class="ajaxuploader-upload">
    <fieldset>
        <legend>{'Step 1/3: Carica un file'|i18n( 'openpa' )}</legend>
        <p>
            <label for="ajaxuploader-file">{'File'|i18n( 'design/admin2/ajaxuploader' )} ({'obbligatorio'|i18n( 'openpa' )})</label>
            <input type="file" name="UploadFile" id="ajaxuploader-file" class="input-required" />
        </p>
        <p>
            <label for="ajaxuploader-name">{'Titolo'|i18n( 'openpa' )}</label>
            <input type="text" name="UploadName" id="ajaxuploader-name" class="box form-control has-default-value" value="{'Il nome verrà generato automaticamente'|i18n( 'openpa' )}" />
        </p>
        <p class="ajaxuploader-button-bar">
            <input type="submit" class="button btn btn-primary pull-right" value="{'Carica'|i18n( 'openpa' )}" />
            <a href="#" class="window-cancel btn btn-danger pull-left">{'Chiudi'|i18n( 'openpa' )}</a>
            <span class="ajaxuploader-error"></span>
        </p>
    </fieldset>
</form>
